/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UApp: typeof import('./node_modules/.pnpm/@nuxt+ui@3.0.2_@babel+parser@7.27.0_embla-carousel@8.5.2_typescript@5.8.2_vite@6.2.4_@t_87d772e460ca07c23a57ac35b1e85194/node_modules/@nuxt/ui/dist/runtime/components/App.vue')['default']
    UButton: typeof import('./node_modules/.pnpm/@nuxt+ui@3.0.2_@babel+parser@7.27.0_embla-carousel@8.5.2_typescript@5.8.2_vite@6.2.4_@t_87d772e460ca07c23a57ac35b1e85194/node_modules/@nuxt/ui/dist/runtime/components/Button.vue')['default']
    ULinkBase: typeof import('./node_modules/.pnpm/@nuxt+ui@3.0.2_@babel+parser@7.27.0_embla-carousel@8.5.2_typescript@5.8.2_vite@6.2.4_@t_87d772e460ca07c23a57ac35b1e85194/node_modules/@nuxt/ui/dist/runtime/components/LinkBase.vue')['default']
  }
}
